In [ ]:
#from which city,state we are receiving most orders
#from which city,state most sellers are there
#from which city, state most customers are there

In [2]:
import pandas as pd
import numpy as np

In [10]:
order_items = pd.read_csv('E:/Projects/ecommerce-sales-analysis/data/raw_data/olist_order_items_dataset.csv',dtype={'price': 'float', 'freight_value': 'float'},
    parse_dates=['shipping_limit_date'])

In [15]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

## From which city , state we are receiving most orders

In [91]:
# for that we need to join order and coustomer table
customers =  pd.read_csv('E:/Projects/ecommerce-sales-analysis/data/raw_data/olist_customers_dataset.csv')

In [92]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [93]:
order = pd.read_csv(r'E:\Projects\ecommerce-sales-analysis\data\raw_data\olist_orders_dataset.csv')

In [94]:
order.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [95]:
order['customer_id'].isin(customers['customer_id']).sum()

99441

In [96]:
orders_customers = pd.merge(order[['order_id','customer_id']],customers[['customer_id','customer_city','customer_state']],on='customer_id')

In [97]:
orders_customers.head()

,order_id,customer_id,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,santo andre,SP

In [98]:
order['order_id'].isin(customers['customer_id'])

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Name: order_id, Length: 99441, dtype: bool

In [99]:
order['order_id'].notna().sum()

99441

In [100]:
(~customers['customer_id'].isna()).sum()

99441

In [101]:
# we can say that customer id can be used for
# calculating the orders recevied from a state without merging with orders table

In [102]:
orders_customers['customer_city'].value_counts()

customer_city
sao paulo           15540
rio de janeiro       6882
belo horizonte       2773
brasilia             2131
curitiba             1521
                    ...
vila nova do sul        1
cuite velho             1
novais                  1
jacuipe                 1
nova vicosa             1
Name: count, Length: 4119, dtype: int64

'Sao paulo' is the city with most orders

In [103]:
orders_customers['customer_state'].value_counts().head()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
Name: count, dtype: int64

'SP' is the state with most orders

In [104]:
states = orders_customers['customer_state'].value_counts()

In [105]:
orders_customers.groupby('customer_state')['customer_city'].nunique()

customer_state
AC      8
AL     68
AM      5
AP      6
BA    353
CE    161
DF      6
ES     95
GO    178
MA    122
MG    745
MS     67
MT    101
PA     89
PB     92
PE    152
PI     72
PR    364
RJ    149
RN     90
RO     35
RR      2
RS    379
SC    240
SE     46
SP    629
TO     56
Name: customer_city, dtype: int64

In [106]:
weighted_states = orders_customers.groupby('customer_state')['customer_city'].nunique()

In [107]:
orders_per_100_cities = (states / weighted_states) * 100

This metric normalizes order volume by the number of cities in each state, allowing a fair comparison across states with different geographic distributions.

Interpretation

States such as DF, RJ, and SP exhibit high order density, indicating stronger e-commerce market penetration and higher purchasing activity per city.

In contrast, some states with a larger number of cities show lower order density, suggesting comparatively lower purchasing activity per city. This may indicate:

lower market penetration

lower purchasing power

logistical or accessibility differences in e-commerce adoption.

In [108]:
orders_per_100_cities.sort_values(ascending= False)

customer_state
DF    35666.666667
RJ     8625.503356
SP     6636.883943
AM     2960.000000
RR     2300.000000
ES     2140.000000
MG     1561.744966
SC     1515.416667
RS     1442.216359
PR     1385.989011
GO     1134.831461
AP     1133.333333
PA     1095.505618
PE     1086.842105
MS     1067.164179
AC     1012.500000
BA      957.507082
MT      898.019802
CE      829.813665
SE      760.869565
RO      722.857143
PI      687.500000
MA      612.295082
AL      607.352941
PB      582.608696
RN      538.888889
TO      500.000000
dtype: float64