In [4]:
#from which city,state we are receiving most orders
#from which city,state most sellers are there
#from which city, state most customers are there
#from which city,state most orders were cancelled
#from which city,state of seller most orders were cancelled

In [5]:
import pandas as pd
import numpy as np

In [6]:
order_items = pd.read_csv('E:/Projects/ecommerce-sales-analysis/data/raw_data/olist_order_items_dataset.csv',dtype={'price': 'float', 'freight_value': 'float'},
    parse_dates=['shipping_limit_date'])

In [7]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

## From which city , state we are receiving most orders

In [8]:
# for that we need to join order and coustomer table
customers =  pd.read_csv('E:/Projects/ecommerce-sales-analysis/data/raw_data/olist_customers_dataset.csv')

In [9]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [10]:
order = pd.read_csv(r'E:\Projects\ecommerce-sales-analysis\data\raw_data\olist_orders_dataset.csv')

In [11]:
order.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [12]:
order['customer_id'].isin(customers['customer_id']).sum()

99441

In [13]:
orders_customers = pd.merge(order[['order_id','customer_id']],customers[['customer_id','customer_city','customer_state']],on='customer_id')

In [14]:
orders_customers.head()

,order_id,customer_id,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,santo andre,SP

In [15]:
order['order_id'].isin(customers['customer_id'])

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Name: order_id, Length: 99441, dtype: bool

In [16]:
order['order_id'].notna().sum()

99441

In [17]:
(~customers['customer_id'].isna()).sum()

99441

In [18]:
# we can say that customer id can be used for
# calculating the orders recevied from a state without merging with orders table

In [19]:
orders_customers['customer_city'].value_counts()

customer_city
sao paulo           15540
rio de janeiro       6882
belo horizonte       2773
brasilia             2131
curitiba             1521
                    ...
vila nova do sul        1
cuite velho             1
novais                  1
jacuipe                 1
nova vicosa             1
Name: count, Length: 4119, dtype: int64

'Sao paulo' is the city with most orders

In [20]:
orders_customers['customer_state'].value_counts().head()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
Name: count, dtype: int64

'SP' is the state with most orders

In [21]:
states = orders_customers['customer_state'].value_counts()

In [22]:
orders_customers.groupby('customer_state')['customer_city'].nunique()

customer_state
AC      8
AL     68
AM      5
AP      6
BA    353
CE    161
DF      6
ES     95
GO    178
MA    122
MG    745
MS     67
MT    101
PA     89
PB     92
PE    152
PI     72
PR    364
RJ    149
RN     90
RO     35
RR      2
RS    379
SC    240
SE     46
SP    629
TO     56
Name: customer_city, dtype: int64

In [23]:
weighted_states = orders_customers.groupby('customer_state')['customer_city'].nunique()

In [24]:
orders_per_100_cities = (states / weighted_states) * 100

This metric normalizes order volume by the number of cities in each state, allowing a fair comparison across states with different geographic distributions.

Interpretation

States such as DF, RJ, and SP exhibit high order density, indicating stronger e-commerce market penetration and higher purchasing activity per city.

In contrast, some states with a larger number of cities show lower order density, suggesting comparatively lower purchasing activity per city. This may indicate:

lower market penetration

lower purchasing power

logistical or accessibility differences in e-commerce adoption.

In [25]:
orders_per_100_cities.sort_values(ascending= False)

customer_state
DF    35666.666667
RJ     8625.503356
SP     6636.883943
AM     2960.000000
RR     2300.000000
ES     2140.000000
MG     1561.744966
SC     1515.416667
RS     1442.216359
PR     1385.989011
GO     1134.831461
AP     1133.333333
PA     1095.505618
PE     1086.842105
MS     1067.164179
AC     1012.500000
BA      957.507082
MT      898.019802
CE      829.813665
SE      760.869565
RO      722.857143
PI      687.500000
MA      612.295082
AL      607.352941
PB      582.608696
RN      538.888889
TO      500.000000
dtype: float64

## from which city,state most sellers are there

In [26]:
sellers = pd.read_csv(r'E:\Projects\ecommerce-sales-analysis\data\raw_data\olist_sellers_dataset.csv')

In [27]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [28]:
orders_seller = pd.merge(order_items[['order_id','seller_id']],sellers[['seller_id','seller_city','seller_state']],on="seller_id")

In [29]:
orders_seller.head()

,order_id,seller_id,seller_city,seller_state
0,00010242fe8c5a6d1ba2dd792cb16214,48436dade18ac8b2bce089ec2a041202,volta redonda,SP
1,00018f77f2f0320c557190d7a144bdd3,dd7ddc04e1b6c2c614352b383efe2d36,sao paulo,SP
2,000229ec398224ef6ca0657da4fc703e,5b51032eddd242adc84c38acab88f23d,borda da mata,MG
3,00024acbcdf0a6daa1e931b038114c75,9d7a1d34a5052409006425275ba1c2b4,franca,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,df560393f3a51e74553ab94004ba5c87,loanda,PR

In [30]:
orders_seller['seller_city'].value_counts()

seller_city
sao paulo          27983
ibitinga            7750
curitiba            3016
santo andre         2964
belo horizonte      2593
                   ...
rio das pedras         1
abadia de goias        1
eusebio                1
condor                 1
avare                  1
Name: count, Length: 611, dtype: int64

Sao paulo is the city from which most sellers are

In [31]:
state_count = orders_seller['seller_state'].value_counts()

SP is the state with most sellers

In [34]:
cities_per_state = orders_seller.groupby('seller_state')['seller_city'].nunique()

In [35]:
sellers_per_100_cities = (state_count/cities_per_state)*100

In [37]:
sellers_per_100_cities.sort_values(ascending=False)

seller_state
MA    40500.000000
SP    30782.375479
DF    29966.666667
PR    12941.791045
RJ    12678.947368
PE    11200.000000
MG    10764.634146
SC     6269.230769
BA     5358.333333
MT     4833.333333
GO     4333.333333
RS     4311.764706
ES     3381.818182
MS     2500.000000
RN     1400.000000
CE     1342.857143
PI     1200.000000
PA      800.000000
PB      760.000000
RO      700.000000
SE      500.000000
AM      300.000000
AC      100.000000
dtype: float64

The above is the seller density of a state

## from which city, state most customers are there

Need to use order dataset as order_items doesn't contain customer_id

In [43]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [42]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [44]:
customers_orders = pd.merge(customers[['customer_id','customer_unique_id','customer_city','customer_state']],order[['order_id','customer_id']],on='customer_id')

In [45]:
customers_orders.head()

,customer_id,customer_unique_id,customer_city,customer_state,order_id
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP,00e7ee1b050b8499577073aeb2a297a1
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f

In [48]:
customers_orders['customer_unique_id'].duplicated().sum()

3345

In [50]:
# unique customer id is the real cusotmer id 
customers_orders.groupby('customer_city')['customer_unique_id'].nunique().sort_values(ascending=False)

customer_city
sao paulo         14984
rio de janeiro     6620
belo horizonte     2672
brasilia           2069
curitiba           1465
                  ...
ibertioga             1
ibiajara              1
ibiara                1
ibicuitinga           1
lagoao                1
Name: customer_unique_id, Length: 4119, dtype: int64

Sao paulo is the city with most customers

In [52]:
customers_orders.groupby('customer_state')['customer_unique_id'].nunique().sort_values(ascending=False)

customer_state
SP    40302
RJ    12384
MG    11259
RS     5277
PR     4882
SC     3534
BA     3277
DF     2075
ES     1964
GO     1952
PE     1609
CE     1313
PA      949
MT      876
MA      726
MS      694
PB      519
PI      482
RN      474
AL      401
SE      342
TO      273
RO      240
AM      143
AC       77
AP       67
RR       45
Name: customer_unique_id, dtype: int64

In [53]:
customers_per_state = customers_orders.groupby('customer_state')['customer_unique_id'].nunique()

In [55]:
cities_per_state_cusotmer =customers_orders.groupby('customer_state')['customer_city'].nunique()

In [61]:
customer_denisty = (customers_per_state/cities_per_state_cusotmer)*100

In [62]:
customer_denisty.sort_values(ascending=False)

customer_state
DF    34583.333333
RJ     8311.409396
SP     6407.313196
AM     2860.000000
RR     2250.000000
ES     2067.368421
MG     1511.275168
SC     1472.500000
RS     1392.348285
PR     1341.208791
AP     1116.666667
GO     1096.629213
PA     1066.292135
PE     1058.552632
MS     1035.820896
AC      962.500000
BA      928.328612
MT      867.326733
CE      815.527950
SE      743.478261
RO      685.714286
PI      669.444444
MA      595.081967
AL      589.705882
PB      564.130435
RN      526.666667
TO      487.500000
dtype: float64

## from which city,state most orders were cancelled

In [63]:
order['order_status'].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [64]:
orders_canceled = order[order['order_status']=='canceled']

In [65]:
customer_who_canceled = pd.merge(orders_canceled[['order_id','customer_id']],customers[['customer_id','customer_city','customer_state']],on='customer_id')

In [66]:
customer_who_canceled['customer_city'].value_counts()

customer_city
sao paulo         140
rio de janeiro     48
belo horizonte     17
guarulhos          13
campinas           11
                 ...
linhares            1
caxambu             1
barra mansa         1
capanema            1
gaspar              1
Name: count, Length: 247, dtype: int64

Sao paulo has most orders canceled

In [67]:
customer_who_canceled['customer_state'].value_counts()

customer_state
SP    327
RJ     86
MG     64
RS     25
PR     22
SC     19
BA     16
GO     13
ES      9
DF      7
CE      7
PE      5
MA      4
PA      4
PI      4
RO      3
PB      2
MT      2
MS      2
RR      1
SE      1
TO      1
AL      1
Name: count, dtype: int64

In [68]:
customers_per_state_canceled = customer_who_canceled['customer_state'].value_counts()

In [70]:
cities_per_state_canceled = customer_who_canceled.groupby('customer_state')['customer_city'].nunique()

In [71]:
cancel_density = (customers_per_state_canceled/cities_per_state_canceled)*100

In [73]:
cancel_density.sort_values(ascending=False)

customer_state
DF    700.000000
SP    359.340659
RJ    318.518519
PR    220.000000
GO    216.666667
PB    200.000000
MA    200.000000
MG    182.857143
ES    180.000000
CE    175.000000
PE    166.666667
RO    150.000000
SC    135.714286
PI    133.333333
BA    133.333333
PA    133.333333
RS    125.000000
SE    100.000000
AL    100.000000
RR    100.000000
MT    100.000000
MS    100.000000
TO    100.000000
dtype: float64

## from which city,state of seller most orders were cancelled

In [ ]:
orders_canceled.set_index

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
397,1b9ecfe83cdc259250e1a8aca174f0ad,6d6b50b66d79f80827b6d96751528d30,canceled,2018-08-04 14:29:27,2018-08-07 04:10:26,NaN,NaN,2018-08-14 00:00:00
613,714fb133a6730ab81fa1d3c1b2007291,e3fe72696c4713d64d3c10afe71e75ed,canceled,2018-01-26 21:34:08,2018-01-26 21:58:39,2018-01-29 22:33:25,NaN,2018-02-22 00:00:00
1058,3a129877493c8189c59c60eb71d97c29,0913cdce793684e52bbfac69d87e91fd,canceled,2018-01-25 13:34:24,2018-01-25 13:50:20,2018-01-26 21:42:18,NaN,2018-02-23 00:00:00
1130,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaN,NaN,NaN,2018-09-12 00:00:00
1801,ed3efbd3a87bea76c2812c66a0b32219,191984a8ba4cbb2145acb4fe35b69664,canceled,2018-09-20 13:54:16,NaN,NaN,NaN,2018-10-17 00:00:00