In [1]:
import pandas as pd

In [55]:
order_items=pd.read_csv(
    '/Users/shamitharamya/Documents/ecommerce-sales-analysis/data/raw_data/olist_order_items_dataset.csv',
    dtype={'price': 'float', 'freight_value': 'float'},
    parse_dates=['shipping_limit_date']
)

In [56]:
orders=pd.read_csv('/Users/shamitharamya/Documents/ecommerce-sales-analysis/data/raw_data/olist_orders_dataset.csv',
                   parse_dates=['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date'])

In [57]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [58]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [59]:
revenue_data=pd.merge(orders[['order_id','order_status','order_purchase_timestamp','customer_id']],order_items[['order_id','product_id','price','freight_value','seller_id']],on='order_id')

In [60]:
revenue_data

,order_id,order_status,order_purchase_timestamp,customer_id,product_id,price,freight_value,seller_id
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-02 10:56:33,9ef432eb6251297304e76186b10a928d,87285b34884572647811a353c7ac498a,29.99,8.72,3504c0cb71d7fa48d967e0e4c94d59d9
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-07-24 20:41:37,b0830fb4747a6c6d20dea0b8c802d7ef,595fac2a385ac33a80bd5114aec74eb8,118.70,22.76,289cdb325fb7e7f891c38608bf9e0962
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-08 08:38:49,41ce2a54c0b03bf3443c3d931a367089,aa4383b373c6aca5d8797843e5594415,159.90,19.22,4869f7a5dfa277a7dca6462dcf3b52b2
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-11-18 19:28:06,f88197465ea7920adcdbec7375364d82,d0b61bfb1de832b15ba9d266ca96e5b0,45.00,27.20,66922902710d126a0e7d26b0e3805106
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-13 21:18:39,8ab97904e6daea8866dbdbc4fb7aad2c,65266b2da20d04dbe00c5c2d3bb7859e,19.90,8.72,2c9e548be18521d1c43cde1c582c6de8
...,...,...,...,...,...,...,...,...
112645,63943bddc261676b46f01ca7ac2f7bd8,delivered,2018-02-06 12:58:58,1fca14ff2861355f6e5f14306ff977a7,f1d4ce8c6dd66c47bbaa8c6781c2a923,174.90,20.10,1f9ab4708f3056ede07124aad39a2554
112646,83c1379a015df1e13d02aae0204711ab,delivered,2017-08-27 14:46:43,1aa71eb042121263aafbe80c1b562c9c,b80910977a37536adeddd63663f916ad,205.99,65.02,d50d79cb34e38265a8649c383dcffd48
112647,11c177c8e97725db2631073c19f07b62,delivered,2018-01-08 21:28:27,b331b74b18dc79bcdf6532d51e1637c1,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,40.59,a1043bafd471dff536d0c462352beb48
112648,11c177c8e97725db2631073c19f07b62,delivered,2018-01-08 21:28:27,b331b74b18dc79bcdf6532d51e1637c1,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,40.59,a1043bafd471dff536d0c462352beb48
112649,66dea50a8b16d9b4dee7af250b4be1a5,delivered,2018-03-08 20:57:30,edb027a75a1449115f6b43211ae02a24,006619bbed68b000c8ba3f8725d5409e,68.50,18.36,ececbfcff9804a2d6b40f589df8eef2b

In [61]:
revenue_data['year']=revenue_data['order_purchase_timestamp'].dt.year

In [62]:
revenue_data['order_status'].value_counts()

order_status
delivered      110197
shipped          1185
canceled          542
invoiced          359
processing        357
unavailable         7
approved            3
Name: count, dtype: int64

In [63]:
revenue_data=revenue_data[revenue_data['order_status']=='delivered']

In [64]:
revenue_data['revenue']=revenue_data['price']+revenue_data['freight_value']

/var/folders/gr/93yw8_tj0dv3xlw_t_hq5yn40000gn/T/ipykernel_1330/2229636876.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  revenue_data['revenue']=revenue_data['price']+revenue_data['freight_value']

In [65]:
#year wise revenue
revenue_data.groupby('year')['revenue'].sum()

year
2016      46653.74
2017    6921535.24
2018    8451584.77
Name: revenue, dtype: float64

In [66]:
#which year has highest revenue
revenue_data.groupby('year')['revenue'].sum().idxmax()

np.int32(2018)

In [67]:
revenue_data['month']=revenue_data['order_purchase_timestamp'].dt.month

/var/folders/gr/93yw8_tj0dv3xlw_t_hq5yn40000gn/T/ipykernel_1330/3976567698.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  revenue_data['month']=revenue_data['order_purchase_timestamp'].dt.month

In [68]:
#month wise revenue
revenue_data.groupby('month')['revenue'].sum()

month
1     1205369.83
2     1237407.73
3     1534929.19
4     1523691.33
5     1695625.92
6     1502028.66
7     1594106.36
8     1631324.00
9      701220.95
10     797607.67
11    1153364.20
12     843097.91
Name: revenue, dtype: float64

In [69]:
#which month has highest revenue
revenue_data.groupby('month')['revenue'].sum().idxmax()

np.int32(5)

In [70]:
#product wise revenue
revenue_data.groupby('product_id')['revenue'].sum()

product_id
00066f42aeeb9f3007548bb9d3f33c38    120.24
00088930e925c41fd95ebfe695fd2655    143.83
0009406fd7479715e4bef61dd91f2462    242.10
000b8f95fcb9e0096488278317764d19    157.00
000d9be29b5207b54e86aa1b1ac54872    218.27
                                     ...
fff6177642830a9a94a0f2cba5e476d1    285.39
fff81cc3158d2725c0655ab9ba0f712c     97.89
fff9553ac224cec9d15d49f5a263411f     43.85
fffdb2d0ec8d6a61f0a0a0db3f25b441    228.82
fffe9eeff12fcbd74a2f2b007dde0c58    303.87
Name: revenue, Length: 32216, dtype: float64

In [71]:
#which product has highest revenue
revenue_data.groupby('product_id')['revenue'].sum().idxmax()

'bb50f2e236e5eea0100680137654686c'

In [72]:
customers=pd.read_csv('/Users/shamitharamya/Documents/ecommerce-sales-analysis/data/raw_data/olist_customers_dataset.csv')

In [73]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [79]:
customer_revenue=pd.merge(customers,revenue_data[['customer_id','revenue']],on='customer_id')

In [80]:
customer_revenue.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,revenue
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,146.87
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,335.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,157.73
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,173.30
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,252.25

In [ ]:
#customer wise purchase amount
customer_revenue.groupby('customer_unique_id')['revenue'].sum()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2     141.90
0000b849f77a49e4a4ce2b2a4ca5be3f      27.19
0000f46a3911fa3c0805444483337064      86.22
0000f6ccb0745a6a4b88665a16c9f078      43.62
0004aac84e0df4da2b147fca70cf8255     196.89
                                     ...
fffcf5a5ff07b0908bd4e2dbc735a684    2067.42
fffea47cd6d3cc0a88bd621562a9d061      84.58
ffff371b4d645b6ecea244b27531430a     112.46
ffff5962728ec6157033ef9805bacc48     133.69
ffffd2657e2aad2907e67c3e9daecbeb      71.56
Name: revenue, Length: 93358, dtype: float64

In [ ]:
#which customer purchasedd more
customer_revenue.groupby('customer_unique_id')['revenue'].sum().idxmax()

'0a0a92112bd4c708ca5fde585afaa872'

In [85]:
#city wise revenue
customer_revenue.groupby('customer_city')['revenue'].sum()

customer_city
abadia dos dourados     413.50
abadiania              1025.52
abaete                 1946.81
abaetetuba             4672.27
abaiara                 332.15
                        ...
xinguara               1608.51
xique-xique             230.56
zacarias                229.85
ze doca                 878.92
zortea                  137.57
Name: revenue, Length: 4085, dtype: float64

In [86]:
#from which city we are getting highest revenue
customer_revenue.groupby('customer_city')['revenue'].sum().idxmax()

'sao paulo'

In [88]:
#state wise revenue
customer_revenue.groupby('customer_state')['revenue'].sum()

customer_state
AC      19575.33
AL      94172.49
AM      27585.47
AP      16141.81
BA     591137.81
CE     266436.77
DF     346123.35
ES     317657.93
GO     334212.35
MA     147803.55
MG    1818891.67
MS     134367.55
MT     181224.42
PA     212023.57
PB     137838.55
PE     308972.05
PI     105178.19
PR     781708.80
RJ    2055401.57
RN     100714.78
RO      56966.00
RR       9039.52
RS     861472.79
SC     595127.78
SE      70289.13
SP    5769703.15
TO      60007.37
Name: revenue, dtype: float64

In [90]:
#from which state we are getting highest revenue
customer_revenue.groupby('customer_state')['revenue'].sum().idxmax()

'SP'

In [91]:
sellers=pd.read_csv('/Users/shamitharamya/Documents/ecommerce-sales-analysis/data/raw_data/olist_sellers_dataset.csv')

In [92]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [93]:
seller_revenue=pd.merge(sellers,revenue_data[['seller_id','revenue']],on='seller_id')

In [94]:
seller_revenue.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state,revenue
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,117.62
1,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,13.22
2,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,115.76
3,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,231.45
4,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,231.45

In [ ]:
#seller wise sales amount
seller_revenue.groupby('seller_id')['revenue'].sum()

seller_id
0015a82c2db000af6aaaf3ae2ecb0532     2748.06
001cca7ae9ae17fb1caed9dfb1094831    33142.90
002100f778ceb8431b7a1020ff7ab48f     1995.16
003554e2dce176b5555353e4f3555ac8      139.38
004c9cd9d87a3c30c522c48c4fc07416    23094.02
                                      ...
ffc470761de7d0232558ba5e786e57b7     1950.22
ffdd9f82b9a447f6f8d4b91554cc7dd3     2828.66
ffeee66ac5d5a62fe688b9d26f83f534     2259.55
fffd5413c0700ac820c7069d66d98c89    11125.30
ffff564a4f9085cd26170f4732393726      474.35
Name: revenue, Length: 2970, dtype: float64

In [96]:
#which seller has maximum sales
seller_revenue.groupby('seller_id')['revenue'].sum().idxmax()

'4869f7a5dfa277a7dca6462dcf3b52b2'

In [97]:
#city wise sales amount
seller_revenue.groupby('seller_city')['revenue'].sum()

seller_city
abadia de goias      185.88
afonso claudio       413.26
aguas claras df       52.78
alambari             219.75
alfenas             7438.93
                     ...
volta redonda      15423.30
votorantim         24598.53
votuporanga        23325.26
xanxere             2091.97
xaxim                410.42
Name: revenue, Length: 595, dtype: float64

In [ ]:
#which city received max sales
seller_revenue.groupby('seller_city')['revenue'].sum().idxmax()

'sao paulo'

In [99]:
#state wise sales amount
seller_revenue.groupby('seller_state')['revenue'].sum()

seller_state
AM       1258.80
BA     297146.93
CE      23724.05
DF     112892.78
ES      58853.49
GO      77089.48
MA      48169.50
MG    1184427.54
MS       9750.65
MT      21623.67
PA       1393.11
PB      17844.43
PE     103486.10
PI       2791.55
PR    1424161.25
RJ     911918.67
RN      11296.71
RO       5474.98
RS     429749.09
SC     717739.37
SE       1924.69
SP    9957056.91
Name: revenue, dtype: float64

In [100]:
#which city received max sales
seller_revenue.groupby('seller_state')['revenue'].sum().idxmax()

'SP'